apiVersion: v1
kind: Service
metadata:
  name: api-exercise
  namespace: api-exercise
spec:
  selector:
    app: api-exercise
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
